AllCops:
  TargetRubyVersion: 2.4

Layout:
  DotPosition:
    EnforcedStyle: trailing
  MultilineMethodCallIndentation:
    EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 125

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/help_scout-sdk.rb'
    - 'spec/**/*_spec.rb'

Naming/MemoizedInstanceVariableName:
    EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: False

Metrics/CyclomaticComplexity:
  Enabled: False

Gemspec/RequiredRubyVersion:
  Enabled: False
